require 'capistrano/setup'
require 'capistrano/deploy'
require 'capistrano/rvm'
require 'capistrano/bundler'
require 'capistrano/rails/assets'
require 'capistrano/faster_assets'
require 'capistrano/rails/migrations'
require 'capistrano/safe_deploy_to'
require 'capistrano/passenger'
require 'capistrano/rails/collection'
Dir.glob('lib/capistrano/tasks/*.rake').each { |r| import r }