# Use the README file as a reference to customize settings.

Project:
  fields:
    default: title, description, url, photo
    form: title, description, url, photo
  relationships: 
  application: Application
