development:
  adapter: mysql2
  database: porfolio_dev
  username: root
  password: root
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: porfolio_test
  username: root
  password: root
  pool: 5
  timeout: 5000

staging:
  adapter: mysql2
  database: porfolio_staging
  username: root
  password: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: porfolio
  username: root
  password: root
  pool: 5
  timeout: 5000
